ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
        path('add_to_cart/<p>',views.add_to_cart,name="add_to_cart"),
        path('cartview',views.cartview,name="cartview"),
        path('cart_remove/<p>',views.cart_remove,name="cart_remove"),
        path('full_remove/<p>',views.full_remove,name="full_remove"),
        path('orderform',views.orderform,name="orderform"),
        path('orderview',views.orderview,name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views

app_name="search"

urlpatterns = [
    path('search',views.search,name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shop"
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('alldetails/<p>',views.alldetails,name="alldetails"),
    path('register',views.register,name="register"),
    path('user_login',views.user_login,name="user_login"),
    path('user_logout',views.user_logout,name="user_logout"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    noofitems = models.IntegerField()
    address = models.TextField()
    phone = models.CharField(max_length=30)
    order_status = models.CharField(max_length=30,default="pending")
    delivery_status = models.CharField(max_length=30,default="pending")
    date_ordered = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/categories',blank=True,null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/products',blank=True,null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Order
from cart.models import Account

def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total += i.quantity*i.product.price

    except:
        pass

    return render(request,'cart.html',{'c':cart,'total':total})

@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(product=product,user=u)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
        cart.save()
    except:
        cart = Cart.objects.create(product=product, user=u, quantity=1)
        cart.save()


    return redirect('cart:cartview')

def cart_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:

        cart=Cart.objects.get(user=user,product=p)
        if cart.quantity>1:
           cart.quantity-=1
           cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')


def full_remove(request,p):
    p=Product.objects.get(name=p)
    user=request.user
    try:

        cart = Cart.objects.get(user=user, product=p)
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cartview')

def orderform(request):
    if(request.method=="POST"):
        a = request.POST['a']
        p = request.POST['p']
        n = request.POST['n']
        u = request.user
        cart = Cart.objects.filter(user=u)


        total = 0
        for i in cart:
            total+=i.quantity*i.product.price
            #check whether user has sufficient amount in his account
        ac=Account.objects.get(acctnum=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:#creates record in order table for each object in cart table for the current user
                o=Order.objects.create(user=u,product=i.product,address=a,phone=n,noofitems=i.quantity,order_status="paid")
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()#clears the cart items for the current user
            msg="Order Placed Successfully"
            return render(request,'orderdetail.html',{'m':msg})
        else:
            msg="Insufficient Amount in User Account.You Cannot Place order"
            return render(request,'orderdetail.html',{'m':msg})
    return render(request,'orderform.html')


def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,'search.html',{'p':product,'query':q})

ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def allcategories(request):
    c = Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})
def alldetails(request,p):
    n = Product.objects.get(name=p)
    return render(request,'details.html',{'n':n})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        e=request.POST['e']
        if(p==cp):
            user=User.objects.create_user(username=u,password=p,email=e)
            user.save()
            return allcategories(request)
        else:
            return HttpResponse("password not matching")
    return render(request,'register.html')
def user_login(request):
    if (request.method == "POST"):
        name=request.POST['u']
        passw=request.POST['p']
        user=authenticate(username=name,password=passw)
        if user:
            login(request,user)
            return allcategories(request)
        else:
            messages.error(request,'Invalid Credentails')

    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Hedvig+Letters+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<body>
<!--<p>WELCOME</p>-->
<!--<i class="fa-regular fa-circle-up"></i>-->
<header>
    <center><img src="{% static 'images/logo1.png' %}" class="mb-2" height="100px" width="100px"></center>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
           {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>&nbsp;&nbsp;{{count}}</a>
        </li>

           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">your orders</a>
        </li>
          {% endif %}

           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_logout' %}">logout</a>
        </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">register</a>
        </li>
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_login' %}">login</a>
        </li>


        {% endif %}

      </ul>

      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}

{% endblock %}
<footer>
<div>
    <div class="footer">
    <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All Rights Reserved.</p>
    </div>
</div>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not c %}
<div class="container mt-3">
    <h3 class="text-center">cart is empty</h3>
    <h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">continue shopping</a></h5>
</div>
{% else %}
<div class="container-fluid m-3">
<div class="row">
    <h4 class="text-center">SHOPPING CART</h4>
    <div class="col-sm-6">
        <table class="table table-bordered">
           <tr><th colspan="5" class="text-center">CART ITEMS</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                <td><b>{{i.product.name}}</b></td>
                <td><b>Product id:{{i.product.id}}</b><br>
                <b>Unit Price:{{i.product.price}}</b><br>
                    <b>Quantity:{{i.quantity}}*{{i.product.price}}</b></td>
                <td><b>Subtotal:{{i.subtotal}}</b></td>
                <td>
                    {% if i.quantity < i.product.stock %}
                    <b></b><a href="{% url 'cart:add_to_cart' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-plus"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a>
            {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:full_remove' i.product.name %}"><i style="color:black;font-size:20px;" class="fa-solid fa-trash-can"></i></a>

                </td>

            </tr>
               {% endif %}
            {% endfor %}
        </table>
    </div>
    <div class="col-sm-4" style="position:relative">
        <table class="table table-bordered">
          <tr><th colspan="4" class="text-center">CHECK OUT</th></tr>

            <tr><td class="text-center"><b>TOTAL:<span class="text-danger">{{total}}</span></b></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-danger text-dark"><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-danger text-dark" style="position:absolute;right:0;"><b>Continue Shopping</b></a>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banr.jpg' %}" height="500px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center">Our Collections</h3>
    <p style="line-height:1.8;text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
        It has survived not only five centuries, but also the leap into electronic typesettingr</p>

</div>


<div class="row">
    {% for i in c %}
    <div class="column">
<div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
   <center> <h5 class="card-title" style="font-weight:bold " >{{i.name}}</h5></center>
    <p class="card-text">{{i.des}}</p>
    <center><a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary">PRODUCTS</a></center>
      </div>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}

ecommerce/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="row">
    <div class="col-sm-4">
      <center>
      <img src="{{n.image.url}}" class="mb-5 mt-5" height="300px" width="250px"></center>
    </div>
    <div class="col-sm-4">
     <div class="card">
  <div class="card-body">
    <h5 class="card-title">{{n.name}}</h5>
    <p class="card-text">{{n.price}}</p>

    <p class="card-text">{{n.desc}}</p>
    {% if user.is_superuser == False %}

    {% if n.stock <= 0 %}
    <h4>Out of Stock</h4>
    {% else %}
   <h4> <a href="{% url 'cart:add_to_cart' n.name %}" class="btn btn-primary">Add To Cart</a></h4>
    {% endif %}

    {% else %}

    {% if n.stock <= 0 %}
    <h4>Out of stock</h4>
    <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>
    {% else %}
    <h4>product in stock</h4>
    <h4><a href="{% url 'admin:index' %}" class="btn btn-secondary mt-4">Add Stock</a></h4>
<!--    {% endif %}-->
    {% endif %}
  </div>
</div>

    </div>

  </div>



{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>LOGIN PAGE</h1>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter the username">
</div>
<div class="mb-3">
  <label class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter the name">
</div>
    <div class="mb-3">
        <label class="form-label">login</label>
        <input type="submit" class="form-control">
    </div>
</form>
{% if messages %}
{% for i in messages %}
<ul>
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

ecommerce/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container fluid mt-4">
<center><h3 class="text-center text-secondary">{{m}}</h3>

</center>
    </div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>ENTER ORDER DETAILS</h1>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="enter the address">
</div>
<div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p" placeholder="enter the phone">
</div>
  <div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="text" class="form-control" name="n" placeholder="enter the account number">
</div>
    <div class="mb-3">
        <label class="form-label"></label>
        <input type="submit" class="form-control">
    </div>
</form>


{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid m-3">
<div class="row">

    <div class="col-sm-5">

<table class="table table-bordered">
    <tr><th colspan="5" class="text-center">YOUR ORDERS</th></tr>

            {% for i in o %}

<tr>
        <td> <img src="{{i.product.image.url}}" height="150px" width="150px"></td>
    <td>{{user.username}}</td>

        <td> <b>address:{{i.address}}</b></br>
        <b>phone:{{i.phone}}</b></br>
        <b>product:{{i.product.name}}</b></br>
            <b>price:{{i.product.price}}</b></br>
            <b>date:{{i.date_ordered}}</b></br>
            <b>status:{{i.delivery_status}}</b>
        </td>
</tr>
{% endfor %}
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <img src="{{c.image.url}}" width="100%" height="450px">
</div>
<div class="container-fluid mt-4" style="margin-bottom:50px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="line-height:1.5;text-align:justify;">{{c.desc}}</p>
</div>
<div class="container-fluid mt-1 rounded rounded-5" style="margin-bottom:100px;">

    <div class="row">
    {% for i in p %}
    <div class="col-sm-4">
<div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top p-2" alt="...">
  <div class="card-body">
   <center> <h4 class="card-title text-center" style="font-weight:bold">{{i.name}}</h4></center>
      <h5 class="text-center">{{i.price}}</h5>
    <center><a href="{% url 'shop:alldetails' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a></center>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>REGISTER HERE</h1>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter username">
</div>
<div class="mb-3">
  <label class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="enter the password">
</div>
    <div class="mb-3">
  <label class="form-label">Confirm password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter the password">
</div>
    <div class="mb-3">
  <label class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="enter the email">
</div>

    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>
</form>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="text-center"><h4>You Have Searched For<span class="text-danger">{{query}}</span></h4></div>
</center>
<div class="container-fluid mt-1 rounded rounded-5" style="margin-bottom:100px;">

    <div class="row">
    {% for i in p %}
    <div class="col-sm-4">
<div class="card mb-5" style="width: 30rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top p-2" alt="...">
  <div class="card-body">
   <center> <h4 class="card-title text-center" style="font-weight:bold">{{i.name}}</h4></center>
      <h5 class="text-center">{{i.price}}</h5>
    <center><a href="{% url 'shop:alldetails' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a></center>
      </div>
    </div>
  </div>
  {% empty %}
        <h4 class="text-center text-danger">No Search Result Found</h4>
       {% endfor %}
</div>
{% endblock %}